on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Ratchet'
    - name: output
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "All done! :-)"
